# Generated by Django 4.0.3 on 2022-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('p1', 'oil painting'), ('p2', 'Watercolor painting '), ('p3', 'spay paintion')], max_length=5)),
                ('image', models.ImageField(upload_to='picimage')),
            ],
        ),
    ]
